local Icons = {
	Text = "󰉿",
	File = "",
	Module = "",
	Namespace = "",
	Package = "",
	Class = "",
	Method = "",
	Property = "󰜢",
	Constructor = "",
	Enum = "",
	Interface = "",
	Function = "󰊕",
	Variable = "",
	Field = "",
	Constant = "",
	String = "",
	Number = "",
	Boolean = "◩",
	Array = "",
	Object = "",
	Key = "",
	Null = "󰟢",
	EnumMember = "",
	Struct = "󰙅",
	Event = "",
	Operator = "",
	Keyword = "󰌋",
	Snippet = "",
	Color = "",
	Reference = "",
	Folder = "",
	TypeParameter = "",
	Value = "󰎠",
	Unit = "",
}

--TypeParameter = "",
--Text = "",
--Variable = "",

return Icons
